DROP DATABASE IF EXISTS [VisionAirport_DWH];
CREATE DATABASE [VisionAirport_DWH];

DROP DATABASE IF EXISTS [VisionAirport_OLTP];
CREATE DATABASE [VisionAirport_OLTP];
GO
USE [VisionAirport_OLTP];
GO

CREATE SCHEMA [RAW];
GO
CREATE SCHEMA [ARCHIVE];
GO
CREATE SCHEMA [CLEANSED];
GO